name: 'COVULOR Plexalyzer'
description: 'Official Plexicus code analyzer for COVULOR cloud service'
author: 'Plexicus'
branding:
  icon: 'shield'
  color: 'blue'
inputs:
  plexalyzer-token:
    description: 'Authentication token for COVULOR cloud service'
    required: true
  repo-id:
    description: 'Repository ID in COVULOR service'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    PLEXALYZER_TOKEN: ${{ inputs.plexalyzer-token }}
    REPO_ID: ${{ inputs.repo-id }}
    ACR_LOGIN_SERVER: $ACR_LOGIN_SERVER
    ACR_USERNAME: $ACR_USERNAME
    ACR_PASSWORD: $ACR_PASSWORD
