# action.yml
name: 'COVULOR Plexalyzer'
description: 'Official Plexicus code analyzer for COVULOR cloud service'
author: 'Plexicus'
branding:
  icon: 'shield'
  color: 'blue'
inputs:
  plexalyzer-token:
    description: 'Authentication token for COVULOR cloud service'
    required: true
  repo-id:
    description: 'Repository ID in COVULOR service'
    required: true
runs:
  using: 'docker'
  image: 'docker://plexicus/plexalyzer:latest'
  env:
    MESSAGE_URL: 'https://api.covulor.plexicus.com/receive_plexalyzer_message'
  args:
    - ${{ inputs.plexalyzer-token }}
    - ${{ inputs.repo-id }}
