# action.yml
name: 'COVULOR Plexalyzer'
description: 'Official Plexicus code analyzer for COVULOR cloud service'
author: 'Plexicus'
branding:
  icon: 'shield'
  color: 'blue'
inputs:
  plexalyzer-token:
    description: 'Authentication token for COVULOR cloud service'
    required: true
  repo-id:
    description: 'Repository ID in COVULOR service'
    required: true
runs:
  using: 'docker'
  image: 'docker://plexicus/plexalyzer:latest'
  entrypoint: '/venvs/plexicus-fastapi/bin/python'
  env:
    PLEXALYZER_TOKEN: ${{ inputs.plexalyzer-token }}
    MESSAGE_URL: 'http://fastapi.covulor-prd.svc.cluster.local:8000/receive_plexalyzer_message'
  args:
    - "/app/analyze.py"
    - "--repository_id"
    - ${{ inputs.repo-id }}
    - "--name"
    - ${{ github.repository }}
    - "--branch"
    - ${{ github.event.pull_request.base.ref }}
    - "--url"
    - ${{ github.event.repository.clone_url }}
