# action.yml
name: 'COVULOR Plexalyzer'
description: 'Official Plexicus code analyzer for COVULOR cloud service'
author: 'Plexicus'
branding:
  icon: 'shield'
  color: 'blue'
inputs:
  plexalyzer-token:
    description: 'Authentication token for COVULOR cloud service'
    required: true
  repo-id:
    description: 'Repository ID in COVULOR service'
    required: true
  repo-name:
    description: 'Name of the repository'
    required: true
  branch:
    description: 'Branch name for the pull request'
    required: true
  url:
    description: 'Clone URL of the repository'
    required: true
  files-path:
    description: 'Path to file containing files list for scanning'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Output Files List for Debugging
      id: output-files-list
      shell: bash
      run: |
        echo "Contents of files list:"
        cat "${{ inputs.files-path }}" || echo "File not found or is empty"

    - name: Run PLEXALYZER Docker Analysis
      shell: bash
      env:
        PLEXALYZER_TOKEN: ${{ inputs.plexalyzer-token }}
        MESSAGE_URL: 'http://fastapi.covulor-prd.svc.cluster.local:8000/receive_plexalyzer_message'
      run: |
        docker run --rm \
          -e PLEXALYZER_TOKEN="$PLEXALYZER_TOKEN" \
          -e MESSAGE_URL="$MESSAGE_URL" \
          -v "${{ inputs.files-path }}:/app/files_to_scan.json" \
          plexicus/plexalyzer:latest \
          /venvs/plexicus-fastapi/bin/python /app/analyze.py \
          --repository_id "${{ inputs.repo-id }}" \
          --name "${{ inputs.repo-name }}" \
          --branch "${{ inputs.branch }}" \
          --url "${{ inputs.url }}" \
          --files "/app/files_to_scan.json"
